### ISSUE TITLE
Feature: How to apply OCR?

### ISSUE THREAD

**Issue by ShaileshSardaTTL** [LynnHaDo/Document-Layout-Analysis#1]
Extract data in data structure.

**Comment by shsagnik** [comment]
This model will only do layout analysis, to do ocr you'll need a separate model.

**Comment by LynnHaDo** [comment]
> This model will only do layout analysis, to do ocr you'll need a separate model.

Yes! There are a bunch of OCR models and libraries available right now (example, [docTR](https://github.com/mindee/doctr)) that can extract data with relatively high precision. After you get the regions from the layout analysis model, you can extract each region's coordinates and apply OCR to any specific regions you want. Hope that helps!

**Comment by ShaileshSardaTTL** [comment]
@LynnHaDo Thank You! If you could provide some information how you customly train the model It would be good to understand better.
