### ISSUE TITLE
Missing folder in dataset

### ISSUE THREAD

**Issue by nlpkiddo-2001** [LynnHaDo/Document-Layout-Analysis#3]
Hi, your guide was clear. But I found a small issue in the [document_layout_analysis.ipynb](https://github.com/LynnHaDo/Document-Layout-Analysis/blob/master/document_layout_analysis.ipynb) file. In this notebook you are accessing a dir called ```annotations```. But in the HF dataset you provided, there is no folder like that. Can you please help me in preparing the dataset

```
import os

for folder in folders:
    try:
        _, _, json_file = next(os.walk(os.path.join(folder, 'annotations')))
        for f in json_file:
            convert_coco_json_to_txt(os.path.join(folder, 'annotations', f), os.path.join(folder, 'labels'))
    except StopIteration:
        print(f"No files found in {os.path.join(folder, 'annotations')}")
```

**Comment by LynnHaDo** [comment]
Hi @nlpkiddo-2001,

Thank you for your interest. Due to storage issues, I did not push the dataset to Github. If you want to train, the sources of datasets are listed under README.md, and you can organize the directories/files in YOLO format, specified by Ultralytics. Hope that helps.
